/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Classroom.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Classroom(props) {
  const { nodes, materials } = useGLTF('./models/Classroom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[6.177, 3.165, -2.642]} rotation={[0, -1.332, 0]} scale={0.827}>
        <group position={[0.026, -3.526, -0.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <mesh geometry={nodes.Mesh005.geometry} material={materials.Cuir} />
          <mesh geometry={nodes.Mesh005_1.geometry} material={materials.Base} />
          <mesh geometry={nodes.Mesh005_2.geometry} material={materials['Ombre GF']} />
          <mesh geometry={nodes.Mesh005_3.geometry} material={materials['Ombre N']} />
        </group>
        <group position={[0, -3.332, 0]} rotation={[Math.PI / 2, 0, 0.705]} scale={0.03}>
          <mesh geometry={nodes.Mesh003.geometry} material={materials.Base} />
          <mesh geometry={nodes.Mesh003_1.geometry} material={materials['Ombre N']} />
        </group>
        <group position={[0.024, -3.409, 0.046]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <mesh geometry={nodes.Mesh009.geometry} material={materials.Base} />
          <mesh geometry={nodes.Mesh009_1.geometry} material={materials['Ombre N']} />
        </group>
      </group>
      <group position={[0.814, 0.012, -3.548]} scale={0.599}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Haut Table']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Ombre 01']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Ombre 02']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.Pied} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['Ombre FC']} />
      </group>
      <group position={[-0.03, -0.229, -3.498]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Ombre 02']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Ombre 01']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Haut Table']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials.Pied} />
      </group>
      <group position={[0.096, 0, 0]} scale={5.675}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Sol} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Mur C']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Mur F']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials['RB C']} />
        <mesh geometry={nodes.Plane_5.geometry} material={materials['RB FC']} />
      </group>
      <group position={[0, 0.336, 0.111]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube005_4.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube005_5.geometry} material={materials.Tableau} />
      </group>
      <group position={[-16.985, 3.242, 0.844]} scale={0.372}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Bois} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Ombre bois  C']} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials['Ombre F']} />
      </group>
      <group position={[-17.54, 0.98, -3.335]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.022}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.072']} />
        <mesh geometry={nodes.Cube028_3.geometry} material={materials['Material.073']} />
        <mesh geometry={nodes.Cube028_4.geometry} material={materials['Material.074']} />
        <mesh geometry={nodes.Cube028_5.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Cube028_6.geometry} material={materials['Material.040']} />
      </group>
      <group position={[1.628, 0, -3.907]} scale={0.74}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.016']} />
      </group>
      <group position={[5.025, 1.871, -2.02]} rotation={[0, 0.234, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube018.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-15.756, 3.696, -5.346]} rotation={[Math.PI / 2, 0, 0]} scale={[1.106, 1.106, 1.647]}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[1.244, 1.746, -3.98]} rotation={[0, -1.378, 0]} scale={0.991}>
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder006_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder006_4.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-2.989, 1.746, 0.437]} rotation={[Math.PI, -1.019, Math.PI]} scale={0.991}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['Material.004']} />
      </group>
      <group position={[1.347, 1.746, 0.392]} rotation={[Math.PI, -1.416, Math.PI]} scale={0.991}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.004']} />
      </group>
      <group position={[1.347, 1.746, 3.396]} rotation={[0, -1.335, 0]} scale={0.833}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-7.102, 1.746, -0.101]} rotation={[0, -1.214, 0]} scale={0.833}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-2.841, 1.746, 4.057]} rotation={[Math.PI, -1.161, Math.PI]} scale={0.833}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-11.274, 1.746, -4.127]} rotation={[0, -1.423, 0]} scale={0.833}>
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-11.289, 1.746, -0.042]} rotation={[Math.PI, -1.378, Math.PI]} scale={0.833}>
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[0.925, 1.648, -3.013]} rotation={[0, -0.158, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-0.447, 0.852, 4.183]} rotation={[0, -0.523, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[1.02, 1.648, 0.287]} rotation={[0, 0.113, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-3.664, 1.648, 0.001]} rotation={[0, -0.304, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-3.203, 1.648, 3.993]} rotation={[0, 0.02, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-7.588, 1.648, 0.545]} rotation={[0, -0.182, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-11.701, 1.648, 0.626]} rotation={[0, -0.182, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-12.136, 1.648, -2.374]} rotation={[0, -0.313, 0]} scale={0.033}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.046']} />
      </group>
      <group position={[-7.438, 2.338, 7.806]}>
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Circle001_3.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-9.411, 0.417, -1.462]} rotation={[0, 0.336, 0]} scale={0.469}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.018']} />
      </group>
      <group position={[-1.645, 0.077, 2.488]} rotation={[0, -0.154, 0]} scale={0.469}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.018']} />
      </group>
      <group position={[5.919, 0.186, 1.417]} rotation={[Math.PI, -0.873, Math.PI]} scale={0.469}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.018']} />
      </group>
      <group position={[-16.985, 3.242, 5.114]} scale={0.372}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.Bois} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['Ombre bois  C']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Ombre F']} />
      </group>
      <group position={[-17.711, 2.327, 1.737]} rotation={[Math.PI / 2, 0, -0.802]} scale={0.409}>
        <mesh geometry={nodes.Circle002.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials['Material.079']} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials['Material.080']} />
        <mesh geometry={nodes.Circle002_3.geometry} material={materials['Material.019']} />
      </group>
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.020']} position={[4.744, 1.878, -1.398]} rotation={[0, 0.435, 0]} scale={[0.39, 0.275, 0.275]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.021']} position={[4.744, 1.904, -1.398]} rotation={[0, 0.825, 0]} scale={[0.39, 0.275, 0.275]} />
      <group position={[7.695, 6.727, 0.761]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.261}>
        <mesh geometry={nodes.Circle003.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Circle003_2.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Circle003_3.geometry} material={materials['Material.030']} />
      </group>
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.034']} position={[-0.945, 0.135, -3.551]} scale={0.532} />
      <group position={[5.812, 7.285, 5.541]} scale={[1, 1, 0.066]}>
        <mesh geometry={nodes.Cube021.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Cube021_3.geometry} material={materials['Material.041']} />
      </group>
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.042']} position={[7.885, 2.338, -5.605]} scale={0.118} />
      <mesh geometry={nodes.Windows2001.geometry} material={materials['Material.031']} position={[-9.759, 4.724, -5.572]} scale={[4, 2, 0.112]} />
      <mesh geometry={nodes.Object.geometry} material={materials['Material.031']} position={[-0.232, 4.724, -5.572]} scale={[4, 2, 0.112]} />
      <mesh geometry={nodes.Object001.geometry} material={materials['Material.024']} position={[-0.232, 4.724, -5.572]} scale={[4, 2, 0.112]} />
      <group position={[0.814, 0.012, -0.019]} scale={0.599}>
        <mesh geometry={nodes.Cube016.geometry} material={materials['Haut Table.001']} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['Ombre 01.001']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['Ombre 02.001']} />
        <mesh geometry={nodes.Cube016_3.geometry} material={materials['Pied.001']} />
        <mesh geometry={nodes.Cube016_4.geometry} material={materials['Ombre FC.001']} />
      </group>
      <group position={[-0.025, -0.228, -0.002]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['Ombre 02.002']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['Ombre 01.002']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials['Haut Table.002']} />
        <mesh geometry={nodes.Cube017_3.geometry} material={materials['Pied.002']} />
      </group>
      <group position={[0.814, 0.012, 3.638]} scale={0.599}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Haut Table.003']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Ombre 01.003']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Ombre 02.003']} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials['Pied.003']} />
        <mesh geometry={nodes.Cube019_4.geometry} material={materials['Ombre FC.002']} />
      </group>
      <group position={[-0.025, -0.228, 3.655]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials['Ombre 02.004']} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['Ombre 01.004']} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials['Haut Table.004']} />
        <mesh geometry={nodes.Cube020_3.geometry} material={materials['Pied.004']} />
      </group>
      <group position={[-3.548, 0.012, 3.638]} scale={0.599}>
        <mesh geometry={nodes.Cube023.geometry} material={materials['Haut Table.005']} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['Ombre 01.005']} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials['Ombre 02.005']} />
        <mesh geometry={nodes.Cube023_3.geometry} material={materials['Pied.005']} />
        <mesh geometry={nodes.Cube023_4.geometry} material={materials['Ombre FC.003']} />
      </group>
      <group position={[-3.548, 0.012, -0.019]} scale={0.599}>
        <mesh geometry={nodes.Cube026.geometry} material={materials['Haut Table.006']} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Ombre 01.006']} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['Ombre 02.006']} />
        <mesh geometry={nodes.Cube026_3.geometry} material={materials['Pied.006']} />
        <mesh geometry={nodes.Cube026_4.geometry} material={materials['Ombre FC.004']} />
      </group>
      <group position={[-3.548, 0.012, -3.548]} scale={0.599}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['Haut Table.007']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['Ombre 01.007']} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['Ombre 02.007']} />
        <mesh geometry={nodes.Cube027_3.geometry} material={materials['Pied.007']} />
        <mesh geometry={nodes.Cube027_4.geometry} material={materials['Ombre FC.005']} />
      </group>
      <group position={[-4.387, -0.228, 3.655]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials['Ombre 02.008']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Ombre 01.008']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Haut Table.008']} />
        <mesh geometry={nodes.Cube029_3.geometry} material={materials['Pied.008']} />
      </group>
      <group position={[-4.387, -0.228, -0.002]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['Ombre 02.009']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['Ombre 01.009']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['Haut Table.009']} />
        <mesh geometry={nodes.Cube030_3.geometry} material={materials['Pied.009']} />
      </group>
      <group position={[-4.393, -0.229, -3.498]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Ombre 02.007']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Ombre 01.007']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['Haut Table.007']} />
        <mesh geometry={nodes.Cube031_3.geometry} material={materials['Pied.007']} />
      </group>
      <group position={[-7.556, 0.012, -3.548]} scale={0.599}>
        <mesh geometry={nodes.Cube032.geometry} material={materials['Haut Table.010']} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['Ombre 01.010']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Ombre 02.010']} />
        <mesh geometry={nodes.Cube032_3.geometry} material={materials['Pied.010']} />
        <mesh geometry={nodes.Cube032_4.geometry} material={materials['Ombre FC.006']} />
      </group>
      <group position={[-7.556, 0.012, -0.019]} scale={0.599}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['Haut Table.011']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['Ombre 01.011']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['Ombre 02.011']} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials['Pied.011']} />
        <mesh geometry={nodes.Cube033_4.geometry} material={materials['Ombre FC.007']} />
      </group>
      <group position={[-7.556, 0.012, 3.638]} scale={0.599}>
        <mesh geometry={nodes.Cube034.geometry} material={materials['Haut Table.012']} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['Ombre 01.012']} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials['Ombre 02.012']} />
        <mesh geometry={nodes.Cube034_3.geometry} material={materials['Pied.012']} />
        <mesh geometry={nodes.Cube034_4.geometry} material={materials['Ombre FC.008']} />
      </group>
      <group position={[-8.401, -0.229, -3.498]}>
        <mesh geometry={nodes.Cube035.geometry} material={materials['Ombre 02.010']} />
        <mesh geometry={nodes.Cube035_1.geometry} material={materials['Ombre 01.010']} />
        <mesh geometry={nodes.Cube035_2.geometry} material={materials['Haut Table.010']} />
        <mesh geometry={nodes.Cube035_3.geometry} material={materials['Pied.010']} />
      </group>
      <group position={[-8.396, -0.228, -0.002]}>
        <mesh geometry={nodes.Cube036.geometry} material={materials['Ombre 02.013']} />
        <mesh geometry={nodes.Cube036_1.geometry} material={materials['Ombre 01.013']} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials['Haut Table.013']} />
        <mesh geometry={nodes.Cube036_3.geometry} material={materials['Pied.013']} />
      </group>
      <group position={[-8.396, -0.228, 3.655]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials['Ombre 02.014']} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['Ombre 01.014']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['Haut Table.014']} />
        <mesh geometry={nodes.Cube037_3.geometry} material={materials['Pied.014']} />
      </group>
      <group position={[-11.714, 0.012, 3.638]} scale={0.599}>
        <mesh geometry={nodes.Cube038.geometry} material={materials['Haut Table.015']} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['Ombre 01.015']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials['Ombre 02.015']} />
        <mesh geometry={nodes.Cube038_3.geometry} material={materials['Pied.015']} />
        <mesh geometry={nodes.Cube038_4.geometry} material={materials['Ombre FC.009']} />
      </group>
      <group position={[-11.714, 0.012, -0.019]} scale={0.599}>
        <mesh geometry={nodes.Cube039.geometry} material={materials['Haut Table.016']} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials['Ombre 01.016']} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials['Ombre 02.016']} />
        <mesh geometry={nodes.Cube039_3.geometry} material={materials['Pied.016']} />
        <mesh geometry={nodes.Cube039_4.geometry} material={materials['Ombre FC.010']} />
      </group>
      <group position={[-11.714, 0.012, -3.548]} scale={0.599}>
        <mesh geometry={nodes.Cube040.geometry} material={materials['Haut Table.017']} />
        <mesh geometry={nodes.Cube040_1.geometry} material={materials['Ombre 01.017']} />
        <mesh geometry={nodes.Cube040_2.geometry} material={materials['Ombre 02.017']} />
        <mesh geometry={nodes.Cube040_3.geometry} material={materials['Pied.017']} />
        <mesh geometry={nodes.Cube040_4.geometry} material={materials['Ombre FC.011']} />
      </group>
      <group position={[-12.553, -0.228, 3.655]}>
        <mesh geometry={nodes.Cube041.geometry} material={materials['Ombre 02.018']} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials['Ombre 01.018']} />
        <mesh geometry={nodes.Cube041_2.geometry} material={materials['Haut Table.018']} />
        <mesh geometry={nodes.Cube041_3.geometry} material={materials['Pied.018']} />
      </group>
      <group position={[-12.553, -0.228, -0.002]}>
        <mesh geometry={nodes.Cube042.geometry} material={materials['Ombre 02.019']} />
        <mesh geometry={nodes.Cube042_1.geometry} material={materials['Ombre 01.019']} />
        <mesh geometry={nodes.Cube042_2.geometry} material={materials['Haut Table.019']} />
        <mesh geometry={nodes.Cube042_3.geometry} material={materials['Pied.019']} />
      </group>
      <group position={[-12.558, -0.229, -3.498]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials['Ombre 02.017']} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['Ombre 01.017']} />
        <mesh geometry={nodes.Cube043_2.geometry} material={materials['Haut Table.017']} />
        <mesh geometry={nodes.Cube043_3.geometry} material={materials['Pied.017']} />
      </group>
      <mesh geometry={nodes.Object002.geometry} material={materials['Material.026']} position={[-9.788, 4.724, -5.572]} scale={[4, 2, 0.112]} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials.Bois} />
      <mesh geometry={nodes.Cube003_2.geometry} material={materials['Ombre bois  C']} />
      <mesh geometry={nodes.Cube003_3.geometry} material={materials['Ombre F']} />
    </group>
  )
}

useGLTF.preload('./models/Classroom.glb')
