/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/8.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Danau(props) {
  const { nodes, materials } = useGLTF('./models/8.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003.geometry} material={materials.deniz} position={[29.685, -4.191, -26.953]} scale={0.01} />
      <mesh geometry={nodes.Plane002001.geometry} material={materials['08 - Default']} position={[30.283, 0.652, 0.593]} rotation={[Math.PI, -0.011, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Plane002002.geometry} material={materials['08 - Default']} position={[30.279, 0.464, -62.262]} rotation={[Math.PI, 0.003, 0]} scale={-0.01} />
      <mesh geometry={nodes.Plane002003.geometry} material={materials['08 - Default']} position={[77.711, 0.265, -27.691]} rotation={[0, -1.567, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./models/8.glb')
